import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from "../styles/PageContent.module.css"
import Layout from '@/components/Layout'
import { useContext, useEffect, useState } from 'react'
import { UserContext } from '@/context/UserContext'
import { InputDropDownTunggal } from '@/components/InputField'
import { TDropDown, TRespDosen } from './CommonTypes'
import axios from 'axios'
import { auth, getToken } from '@/utils/token'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const {role, nip} = useContext(UserContext);

    const [loading, setLoading] = useState<boolean>(false);
    /* getALlDosen -> admin pilih dosen yang mau diinputkan datanya */
    const [dosenData, setDosenData] = useState<TDropDown[]>([]);
    const [chosenNip, setChosenNip] = useState<string>("");
    useEffect(() => {
        const getAllDosen = async () => {
            setLoading(true);
            const res = await axios.get(`${process.env.NEXT_PUBLIC_BASE_URL}/api/v1/dosen/getAllDosen`, auth);
            const data:TRespDosen = res?.data;
            let dosenDD = [];
            for (let i = 0; i < data.count; i++) {
                dosenDD.push({value: data.data[i].nip, label: data.data[i].nama});
            }
            setDosenData(dosenDD);
            setLoading(false);
        }

        if (role === 1) {
            getAllDosen();
        }
    }, [role])

    const generateCV = async () => {
        const formData = new FormData();
        if (role === 2) {
            formData.append("nip", nip);
        } else {
            formData.append("nip", chosenNip);
        }

        await axios.post(`${process.env.NEXT_PUBLIC_BASE_URL}/api/v1/cv/generate`, formData, {
            headers: {Authorization: `Bearer ${getToken()}`},
            responseType: 'blob'
        })
        .then((res) => res.data)
        .then((blob) => {
            const url = window.URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.setAttribute('download', 'cv.docx');
            document.body.appendChild(link);
            link.click();
            link.remove();
        })
        .catch(err => console.log(err))
    }

    return (
        <>
            <Head>
                <title>Beranda</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Layout>
                    <div className={styles.page}>
                        <div className={styles.top}>
                            <div className={styles.current_page}>Generate CV</div>
                        </div>
                        <div className={styles.cvBox}>
                            <img src="/cv_illustration.png" alt="generate cv" /> 
                            <div>
                                {role===1 ? 
                                    <InputDropDownTunggal 
                                        loading={loading}
                                        label="Dosen"
                                        optionsData={dosenData}
                                        nip={chosenNip}
                                        setNip={setChosenNip} /> 
                                    : ""
                                }
                                <button onClick={generateCV}>Generate CV</button>
                            </div>
                        </div>
                    </div>
                </Layout>
            </main>
        </>
    )
}
