import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Sidebar } from '@/components/Sidebar'
import styles from "../styles/PageContent.module.css"
import Layout from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>Beranda</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Layout>
                    <div className={styles.page}>
                        Home page
                    </div>
                </Layout>
            </main>
        </>
    )
}
